name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy code to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          "mkdir -p ${{ secrets.APP_DIR }}"
          
          rsync -avz --exclude '.git*' --exclude '__pycache__' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.APP_DIR }}/
      - name: Deploy on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd $APP_DIR
            cd NHL-portfolio-frontend
            # Собираем образ из корня репозитория, где лежит Dockerfile
            docker build -t nhl-frontend -f Dockerfile .
            
            # Останавливаем старый контейнер, если есть
            docker rm -f nhl-frontend || true
      
            # Запускаем новый
            docker run -d -p 80:80 --name nhl-frontend nhl-frontend
          EOF

